### PR TITLE
Fix blocking in plane of earth (I think)

### LINKED ISSUE #2065: Earth plane ceiling collapsing doesn't reblock previously dug out squares
This allows monsters to gaze attack you through the stone, you to see through the stone as if it isn't there, and for monsters to hit you with reach attacks through the stone.

### PR DESCRIPTION
**Pull request by NeroOneTrueKing**
Closes #2065

### CODE REVIEW

File: src/dig.c [hunk 1]
```diff
@@ -85,6 +85,11 @@ mkcavepos(x, y, dist, waslit, rockit)
     if(Blind)
 	feel_location(x, y);
     else newsym(x,y);
+
+	if (rockit)
+		block_point(x, y);
+	else
+		unblock_point(x, y);
```
Comment (Chris-plus-alphanumericgibberish) [inline src/dig.c:92]: I think this needs to check if(!does_block()). There might hypothetically be a boulder on that spot.

File: src/dig.c [hunk 2]
```diff
@@ -2284,13 +2289,17 @@ int oldy;
...
 			levl[tx][ty].typ = STONE;
+			block_point(tx, ty);
+		}
 	/* dig out around new position */
 	for (tx = max(0, mtmp->mx-1); tx < min(COLNO, mtmp->mx+1); tx++)
 	for (ty = max(0, mtmp->my-1); ty < min(ROWNO, mtmp->my+1); ty++)
-		if (levl[tx][ty].typ == STONE && may_dig(tx, ty))
+		if (levl[tx][ty].typ == STONE && may_dig(tx, ty)) {
 			levl[tx][ty].typ = CORR;
+			unblock_point(tx, ty);
```
Comment (Chris-plus-alphanumericgibberish) [inline src/dig.c:2301]: This may also need if(!does_block())

**Review by Chris-plus-alphanumericgibberish — COMMENTED** [review]
I think I did the commenting wrong :(

**Review by Chris-plus-alphanumericgibberish — APPROVED** [review]
